package com.auditx.parser.service;

import com.auditx.common.constants.KafkaTopics;
import com.auditx.common.dto.RawEventDto;
import com.auditx.common.dto.StructuredEventDto;
import com.auditx.common.util.IdempotencyKeyGenerator;
import com.auditx.parser.model.AuditEventDocument;
import com.auditx.parser.model.RawLogDocument;
import com.auditx.parser.repository.AuditEventRepository;
import com.auditx.parser.repository.RawLogRepository;
import com.auditx.parser.strategy.ParsingStrategy;
import com.auditx.parser.strategy.ParsingStrategyRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.mongodb.core.ReactiveMongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;

import java.time.Instant;
import java.util.Optional;

@Service
public class ParserService {

    private static final Logger log = LoggerFactory.getLogger(ParserService.class);

    private final ParsingStrategyRegistry strategyRegistry;
    private final AuditEventRepository auditEventRepository;
    private final RawLogRepository rawLogRepository;
    private final KafkaTemplate<String, StructuredEventDto> kafkaTemplate;
    private final ReactiveMongoTemplate reactiveMongoTemplate;

    public ParserService(ParsingStrategyRegistry strategyRegistry,
                         AuditEventRepository auditEventRepository,
                         RawLogRepository rawLogRepository,
                         KafkaTemplate<String, StructuredEventDto> kafkaTemplate,
                         ReactiveMongoTemplate reactiveMongoTemplate) {
        this.strategyRegistry = strategyRegistry;
        this.auditEventRepository = auditEventRepository;
        this.rawLogRepository = rawLogRepository;
        this.kafkaTemplate = kafkaTemplate;
        this.reactiveMongoTemplate = reactiveMongoTemplate;
    }

    public Mono<Void> process(RawEventDto event) {
        long startTime = System.currentTimeMillis();
        String payload = event.payload();
        String incomingEventId = event.eventId();
        String tenantId = event.tenantId();

        Optional<ParsingStrategy> strategyOpt = strategyRegistry.find(payload);

        if (strategyOpt.isPresent()) {
            ParsingStrategy strategy = strategyOpt.get();
            StructuredEventDto dto = strategy.parse(payload);

            // Use incoming eventId if present, otherwise use the one generated by the strategy
            String eventId = (incomingEventId != null && !incomingEventId.isBlank())
                    ? incomingEventId
                    : dto.eventId();

            // Rebuild dto with the resolved eventId
            StructuredEventDto resolved = new StructuredEventDto(
                    eventId,
                    dto.tenantId() != null ? dto.tenantId() : tenantId,
                    dto.userId(),
                    dto.action(),
                    dto.sourceIp(),
                    dto.outcome(),
                    dto.timestamp(),
                    null,
                    null,
                    null
            );

            String resolvedTenantId = resolved.tenantId();
            String strategyName = strategy.getClass().getSimpleName();

            Query query = Query.query(Criteria.where("eventId").is(eventId));
            Update update = new Update()
                    .setOnInsert("eventId", eventId)
                    .setOnInsert("tenantId", resolvedTenantId)
                    .setOnInsert("userId", resolved.userId())
                    .setOnInsert("action", resolved.action())
                    .setOnInsert("sourceIp", resolved.sourceIp())
                    .setOnInsert("outcome", resolved.outcome())
                    .setOnInsert("timestamp", resolved.timestamp())
                    .setOnInsert("parseStatus", "SUCCESS");

            return reactiveMongoTemplate.upsert(query, update, AuditEventDocument.class)
                    .then(Mono.fromRunnable(() -> kafkaTemplate.send(KafkaTopics.STRUCTURED_EVENTS, eventId, resolved)))
                    .then(Mono.fromRunnable(() -> {
                        long durationMs = System.currentTimeMillis() - startTime;
                        log.info("{{\"eventId\":\"{}\",\"tenantId\":\"{}\",\"strategy\":\"{}\",\"parseStatus\":\"SUCCESS\",\"durationMs\":{}}}",
                                eventId, resolvedTenantId, strategyName, durationMs);
                    }))
                    .then();
        } else {
            String eventId = (incomingEventId != null && !incomingEventId.isBlank())
                    ? incomingEventId
                    : IdempotencyKeyGenerator.generate();

            RawLogDocument rawLog = new RawLogDocument();
            rawLog.setEventId(eventId);
            rawLog.setTenantId(tenantId);
            rawLog.setPayload(payload);
            rawLog.setParseStatus("FAILED");
            rawLog.setReceivedAt(Instant.now());

            return rawLogRepository.save(rawLog)
                    .then(Mono.fromRunnable(() -> {
                        long durationMs = System.currentTimeMillis() - startTime;
                        log.warn("{{\"eventId\":\"{}\",\"tenantId\":\"{}\",\"strategy\":\"none\",\"parseStatus\":\"FAILED\",\"durationMs\":{}}}",
                                eventId, tenantId, durationMs);
                    }))
                    .then();
        }
    }
}
